name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:
 
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: 'docker build -t ${{secrets.CI_REGISTRY_USER}}/calculadora-html:latest .'
      - run: 'docker login -u ${{secrets.CI_REGISTRY_USER}} -p ${{secrets.CI_REGISTRY_PASSWORD}}'
      - run: 'docker push ${{secrets.CI_REGISTRY_USER}}/calculadora-html:latest'
      
      
  test-owasp-job:
        runs-on: ubuntu-latest
        steps:
        - name: OWASP ZAP Baseline Scan
          uses: zaproxy/action-baseline@v0.7.0
          with:
            token: ${{secrets.CI_GIT_TOKEN}}
            target: ${{secrets.CI_URL_NGROK}}
            docker_name: owasp/zap2docker-stable
            issue_title: ZAP Scan Baseline Report=
            allow_issue_writing: true
        - run: echo "Teste DAST"
        
  test-Snyk-job:
        runs-on: ubuntu-latest
        steps:
        - name: Snyk
          # You may pin to the exact commit or the version.
          # uses: snyk/actions@7fad562681122205233d1242c3bb39598c5393da
          uses: snyk/actions@0.3.0
          with:
            # Which Snyk command to run, defaults to test
            command: test
            # Additional arguments to pass to Snyk
        - run: echo "SAST"
     
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Finalizado"
