name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:
 
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: 'docker build -t ${{secrets.CI_REGISTRY_USER}}/calculadora-html:latest .'
      - run: 'docker login -u ${{secrets.CI_REGISTRY_USER}} -p ${{secrets.CI_REGISTRY_PASSWORD}}'
      - run: 'docker push ${{secrets.CI_REGISTRY_USER}}/calculadora-html:latest'
      
      
  test-owasp-job:
        runs-on: ubuntu-latest
        steps:
        - name: OWASP ZAP Baseline Scan
          uses: zaproxy/action-baseline@v0.7.0
          with:
            token: ${{secrets.CI_GIT_TOKEN}}
            target: ${{secrets.CI_URL_NGROK}}
            docker_name: owasp/zap2docker-stable
            issue_title: ZAP Scan Baseline Report=
            allow_issue_writing: true
        - run: echo "Teste DAST"
        
  test-bandit-job:
        runs-on: ubuntu-latest
        steps:
        - name: Bandit Scan
          # You may pin to the exact commit or the version.
          # uses: shundor/python-bandit-scan@9cc5aa4a006482b8a7f91134412df6772dbda22c
          uses: shundor/python-bandit-scan@v1.0
          with:
            # File or directory to run bandit on
            path: .
            # Report only issues of a given severity level or higher. Can be LOW, MEDIUM or HIGH. Default is UNDEFINED (everything)
            level: UNDEFINED
            # Report only issues of a given confidence level or higher. Can be LOW, MEDIUM or HIGH. Default is UNDEFINED (everything)
            confidence: UNDEFINED
            # comma-separated list of paths (glob patterns supported) to exclude from scan (note that these are in addition to the excluded paths provided in the config file) (default: .svn,CVS,.bzr,.hg,.git,__pycache__,.tox,.eggs,*.egg)
            excluded_paths: DEFAULT
            # exit with 0, even with results found
            exit_zero: DEFAULT
            # comma-separated list of test IDs to skip
            skips: DEFAULT
            # path to a .bandit file that supplies command line arguments
            ini_path: DEFAULT
            # Github token of the repository (automatically created by Github)
            GITHUB_TOKEN: ${{secrets.CI_GIT_TOKEN}}
        - run: echo "SAST"
     
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Finalizado"
