name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:
 
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: 'docker build -t ${{secrets.CI_REGISTRY_USER}}/calculadora-html:latest .'
      - run: 'docker login -u ${{secrets.CI_REGISTRY_USER}} -p ${{secrets.CI_REGISTRY_PASSWORD}}'
      - run: 'docker push ${{secrets.CI_REGISTRY_USER}}/calculadora-html:latest'
      
      
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: Calculadora_html.html
     
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Finalizado"
