name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:
 
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: 'docker build -t ${{secrets.CI_REGISTRY_USER}}/calculadora-html:latest .'
      - run: 'docker login -u ${{secrets.CI_REGISTRY_USER}} -p ${{secrets.CI_REGISTRY_PASSWORD}}'
      - run: 'docker push ${{secrets.CI_REGISTRY_USER}}/calculadora-html:latest'
      
      
  bandiy-job:
        runs-on: ubuntu-latest
        steps:
         - name: Bandit Scan
         - uses: shundor/python-bandit-scan@v1.0
           with:
                path: .
                # Report only issues of a given severity level or higher. Can be LOW, MEDIUM or HIGH. Default is UNDEFINED (everything)
                level: UNDEFINED
                # Report only issues of a given confidence level or higher. Can be LOW, MEDIUM or HIGH. Default is UNDEFINED (everything)
                confidence: UNDEFINED
                # comma-separated list of paths (glob patterns supported) to exclude from scan (note that these are in addition to the excluded paths provided in the config file) (default: .svn,CVS,.bzr,.hg,.git,__pycache__,.tox,.eggs,*.egg)
                excluded_paths: DEFAULT
                # exit with 0, even with results found
                exit_zero: DEFAULT
                # comma-separated list of test IDs to skip
                skips: DEFAULT
                # path to a .bandit file that supplies command line arguments
                ini_path: DEFAULT
                # Github token of the repository (automatically created by Github)
                # Github token of the repository (automatically created by Github)
                GITHUB_TOKEN: 
     
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Finalizado"
